services:
  - type: web
    name: kitian-backend
    env: docker
    branch: main
    plan: free
    region: ohio
    dockerfilePath: Dockerfile
    envVars:
      - key: KITIAN_PORT
        value: "8080"
